"""Reproduces the Session 06 rung-1-vs-reference-model agreement table and
additionally computes rung 2 (embeddings) and, optionally, rung 3 (a local
LLM via Ollama) agreement against the same reference lists.

OPUS_REFERENCE below is recorded output from a manual Claude Opus session
(S06), not generated by this script, and is not ground truth: rungs are
compared to it by agreement, never "accuracy". Output is skill ids and
counts only, never resume text.

Rung 3 is opt-in via --rungs (e.g. --rungs 1,2,3) and supports a model
override via --model. A rung 3 run also writes a JSON file under results/
(gitignored) with per-resume latency, failures, and provenance -- see
build_results_payload().
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from datetime import UTC, datetime
from importlib.metadata import version as pkg_version
from pathlib import Path
from typing import Any

from compass.eval.agreement import AggregateAgreement, PerResumeAgreement, compute_agreement
from compass.eval.extraction import (
    Rung3Results,
    failed_seconds,
    get_server_version,
    latency_summary,
    load_resume_extractions,
    load_resume_texts,
    run_rung3,
)
from compass.extract import ollama_llm
from compass.taxonomy.loader import load_taxonomy

ROOT = Path(__file__).resolve().parent.parent
TAXONOMY_DIR = ROOT / "taxonomy"
STRIPPED_DIR = ROOT / "resumes_stripped_v2"
RESULTS_DIR = ROOT / "results"

VALID_RUNGS = ("1", "2", "3")

# S06 reference output, skill ids only, no PII
OPUS_REFERENCE: dict[str, set[str]] = {
    "prac_001": {
        "api_integration",
        "ci_cd",
        "data_visualisation",
        "git",
        "javascript",
        "linux",
        "logging_monitoring",
        "mysql",
        "rest_api",
        "sql",
    },
    "prac_006": {"computer_vision", "python", "pytorch"},
    "prac_007": {"aws", "ci_cd", "git", "javascript"},
    "my_resume": {
        "agent_frameworks",
        "api_integration",
        "ci_cd",
        "data_visualisation",
        "django",
        "docker",
        "fastapi",
        "feature_engineering",
        "git",
        "llm_integration",
        "logging_monitoring",
        "mlops",
        "model_evaluation",
        "model_serving",
        "mysql",
        "nlp",
        "numpy",
        "pandas",
        "postgresql",
        "python",
        "pytorch",
        "rag",
        "scikit_learn",
        "selenium",
        "sql",
        "statistics",
        "streamlit",
        "time_series",
        "unit_testing",
        "vector_db",
        "web_scraping",
        "xgboost",
    },
    "prac_014": {
        "api_integration",
        "git",
        "javascript",
        "postgresql",
        "rest_api",
        "sql",
        "web_scraping",
    },
    "prac_018": {
        "api_integration",
        "beautifulsoup",
        "flask",
        "javascript",
        "linux",
        "logging_monitoring",
        "python",
        "web_scraping",
    },
}

# Session 06 canary — the rung-1-vs-reference aggregate this script must
# reproduce exactly on the current taxonomy. A mismatch means the S06
# table is no longer reproducible and is a bigger finding than any rung 2
# number — report it, do not silently move on.
S06_CANARY = {
    "total_candidate": 61,
    "total_reference": 64,
    "total_agreed": 51,
    "micro_jaccard": 0.69,
}
CANARY_TOLERANCE = 0.01  # micro_jaccard only; counts must match exactly


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--own-resume",
        type=Path,
        required=True,
        help="Path to the own-resume file (mapped to the my_resume reference key).",
    )
    parser.add_argument(
        "--rungs",
        type=str,
        default="1,2",
        help="Comma-separated list of rungs to run: 1, 2, and/or 3 (default: 1,2).",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Ollama model override for rung 3. Only valid when rung 3 is selected.",
    )
    args = parser.parse_args(argv)

    rungs = [r.strip() for r in args.rungs.split(",") if r.strip()]
    invalid = [r for r in rungs if r not in VALID_RUNGS]
    if invalid:
        parser.error(
            f"invalid --rungs value(s): {', '.join(invalid)} (valid values: "
            f"{', '.join(VALID_RUNGS)})"
        )
    if args.model is not None and "3" not in rungs:
        parser.error("--model is only valid when rung 3 is selected (--rungs must include 3)")

    args.rungs = rungs
    return args


def build_resume_paths(own_resume: Path) -> dict[str, Path]:
    return {
        "prac_001": STRIPPED_DIR / "prac_001.pdf",
        "prac_006": STRIPPED_DIR / "prac_006.pdf",
        "prac_007": STRIPPED_DIR / "prac_007.docx",
        "my_resume": own_resume,
        "prac_014": STRIPPED_DIR / "prac_014.pdf",
        "prac_018": STRIPPED_DIR / "prac_018.pdf",
    }


def print_table(per_resume: list[PerResumeAgreement], aggregate: AggregateAgreement) -> None:
    print(f"  {'file':<12} {'candidate':>9} {'reference':>9} {'agreed':>6} {'jaccard':>7}")
    for row in per_resume:
        print(
            f"  {row.file:<12} {row.candidate_count:>9} {row.reference_count:>9} "
            f"{row.agreed_count:>6} {row.jaccard:>7.2f}"
        )
    print(
        f"  aggregate: total_candidate={aggregate.total_candidate} "
        f"total_reference={aggregate.total_reference} "
        f"total_agreed={aggregate.total_agreed} "
        f"precision_analogue={aggregate.precision_analogue:.2f} "
        f"recall_analogue={aggregate.recall_analogue:.2f} "
        f"micro_jaccard={aggregate.micro_jaccard:.2f}"
    )


def check_canary(aggregate: AggregateAgreement) -> bool:
    mismatches = []
    if aggregate.total_candidate != S06_CANARY["total_candidate"]:
        mismatches.append(
            f"total_candidate: expected {S06_CANARY['total_candidate']}, "
            f"got {aggregate.total_candidate}"
        )
    if aggregate.total_reference != S06_CANARY["total_reference"]:
        mismatches.append(
            f"total_reference: expected {S06_CANARY['total_reference']}, "
            f"got {aggregate.total_reference}"
        )
    if aggregate.total_agreed != S06_CANARY["total_agreed"]:
        mismatches.append(
            f"total_agreed: expected {S06_CANARY['total_agreed']}, got {aggregate.total_agreed}"
        )
    if abs(aggregate.micro_jaccard - S06_CANARY["micro_jaccard"]) > CANARY_TOLERANCE:
        mismatches.append(
            f"micro_jaccard: expected {S06_CANARY['micro_jaccard']} "
            f"(tolerance {CANARY_TOLERANCE}), got {aggregate.micro_jaccard:.4f}"
        )

    if mismatches:
        print("CANARY MISMATCH")
        for mismatch in mismatches:
            print(f"  {mismatch}")
        return False
    return True


def build_results_payload(
    *,
    model: str,
    prompt_version: str,
    taxonomy_version: str,
    ollama_package_version: str,
    ollama_server_version: str | None,
    rung3_result: Rung3Results,
    aggregate: AggregateAgreement,
) -> dict[str, Any]:
    """JSON-serialisable rung 3 run record. Skill ids and resume ids only --
    never resume text.
    """
    median_seconds, max_seconds = latency_summary(
        rung3_result.seconds_by_resume, rung3_result.failures
    )

    per_resume = {
        key: {
            "skills": sorted(skills),
            "seconds": rung3_result.seconds_by_resume.get(key),
        }
        for key, skills in rung3_result.skills_by_resume.items()
    }

    return {
        "timestamp": datetime.now(UTC).isoformat(),
        "model": model,
        "prompt_version": prompt_version,
        "taxonomy_version": taxonomy_version,
        "ollama_package_version": ollama_package_version,
        "ollama_server_version": ollama_server_version,
        "warmup_seconds": rung3_result.warmup_seconds,
        "per_resume": per_resume,
        "failures": rung3_result.failures,
        "failed_seconds": failed_seconds(rung3_result.seconds_by_resume, rung3_result.failures),
        "aggregate": {
            **asdict(aggregate),
            "latency_median_seconds": median_seconds,
            "latency_max_seconds": max_seconds,
        },
    }


def write_results_file(payload: dict[str, Any], results_dir: Path = RESULTS_DIR) -> Path:
    results_dir.mkdir(parents=True, exist_ok=True)
    model_slug = str(payload["model"]).replace(":", "-").replace("/", "-")
    timestamp_slug = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    path = results_dir / f"rung3_{model_slug}_{timestamp_slug}.json"
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    return path


def print_rung_section(
    label: str,
    per_resume: list[PerResumeAgreement],
    aggregate: AggregateAgreement,
    printed_any: bool,
) -> bool:
    if printed_any:
        print()
    print(label)
    print_table(per_resume, aggregate)
    return True


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    taxonomy = load_taxonomy(TAXONOMY_DIR / "skills.yaml", TAXONOMY_DIR / "roles.yaml")
    resume_paths = build_resume_paths(args.own_resume)

    rung1_skills: dict[str, set[str]] = {}
    rung2_skills: dict[str, set[str]] = {}
    texts: dict[str, str] = {}
    printed_any = False

    if "1" in args.rungs or "2" in args.rungs:
        rung1_skills, rung2_skills, texts = load_resume_extractions(taxonomy, resume_paths)

    if "1" in args.rungs:
        rung1_per_resume, rung1_aggregate = compute_agreement(rung1_skills, OPUS_REFERENCE)
        if not check_canary(rung1_aggregate):
            return 1
        printed_any = print_rung_section(
            "rung 1 (gazetteer) vs reference:", rung1_per_resume, rung1_aggregate, printed_any
        )

    if "2" in args.rungs:
        rung2_per_resume, rung2_aggregate = compute_agreement(rung2_skills, OPUS_REFERENCE)
        printed_any = print_rung_section(
            "rung 2 (embeddings) vs reference:", rung2_per_resume, rung2_aggregate, printed_any
        )

    if "3" in args.rungs:
        if not texts:
            texts = load_resume_texts(resume_paths)

        model = ollama_llm.resolved_model(args.model)
        if printed_any:
            print()
        print(f"rung 3 warm-up ({model}): loading model into memory (untimed, not in latency)...")
        rung3_result = run_rung3(taxonomy, texts, model=args.model)
        print(f"  warm-up took {rung3_result.warmup_seconds:.2f}s")

        reference_subset = {
            key: ref for key, ref in OPUS_REFERENCE.items() if key in rung3_result.skills_by_resume
        }
        rung3_per_resume, rung3_aggregate = compute_agreement(
            rung3_result.skills_by_resume, reference_subset
        )
        printed_any = print_rung_section(
            f"rung 3 (ollama:{model}) vs reference:", rung3_per_resume, rung3_aggregate, printed_any
        )

        if rung3_result.failures:
            print(f"  failures: {len(rung3_result.failures)}")
            failure_seconds = failed_seconds(rung3_result.seconds_by_resume, rung3_result.failures)
            for key, message in sorted(rung3_result.failures.items()):
                print(f"    {key} ({failure_seconds[key]:.2f}s): {message}")

        median_seconds, max_seconds = latency_summary(
            rung3_result.seconds_by_resume, rung3_result.failures
        )
        print(f"  latency (successful calls): median={median_seconds:.2f}s max={max_seconds:.2f}s")

        config = ollama_llm.rung3_config()
        payload = build_results_payload(
            model=model,
            prompt_version=config["prompt_version"],
            taxonomy_version=taxonomy.taxonomy_version,
            ollama_package_version=pkg_version("ollama"),
            ollama_server_version=get_server_version(config["host"]),
            rung3_result=rung3_result,
            aggregate=rung3_aggregate,
        )
        results_path = write_results_file(payload)
        print(f"  results written to {results_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
