"""Reproduces the Session 06 rung-1-vs-reference-model agreement table and
additionally computes rung 2 (embeddings) agreement against the same
reference lists.

OPUS_REFERENCE below is recorded output from a manual Claude Opus session
(S06), not generated by this script, and is not ground truth: rungs are
compared to it by agreement, never "accuracy". Output is skill ids and
counts only, never resume text.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from compass.eval.agreement import AggregateAgreement, PerResumeAgreement, compute_agreement
from compass.extract import embeddings, gazetteer
from compass.resume_intake.text import extract_resume_text
from compass.taxonomy.loader import load_taxonomy

ROOT = Path(__file__).resolve().parent.parent
TAXONOMY_DIR = ROOT / "taxonomy"
STRIPPED_DIR = ROOT / "resumes_stripped_v2"

# S06 reference output, skill ids only, no PII
OPUS_REFERENCE: dict[str, set[str]] = {
    "prac_001": {
        "api_integration",
        "ci_cd",
        "data_visualisation",
        "git",
        "javascript",
        "linux",
        "logging_monitoring",
        "mysql",
        "rest_api",
        "sql",
    },
    "prac_006": {"computer_vision", "python", "pytorch"},
    "prac_007": {"aws", "ci_cd", "git", "javascript"},
    "my_resume": {
        "agent_frameworks",
        "api_integration",
        "ci_cd",
        "data_visualisation",
        "django",
        "docker",
        "fastapi",
        "feature_engineering",
        "git",
        "llm_integration",
        "logging_monitoring",
        "mlops",
        "model_evaluation",
        "model_serving",
        "mysql",
        "nlp",
        "numpy",
        "pandas",
        "postgresql",
        "python",
        "pytorch",
        "rag",
        "scikit_learn",
        "selenium",
        "sql",
        "statistics",
        "streamlit",
        "time_series",
        "unit_testing",
        "vector_db",
        "web_scraping",
        "xgboost",
    },
    "prac_014": {
        "api_integration",
        "git",
        "javascript",
        "postgresql",
        "rest_api",
        "sql",
        "web_scraping",
    },
    "prac_018": {
        "api_integration",
        "beautifulsoup",
        "flask",
        "javascript",
        "linux",
        "logging_monitoring",
        "python",
        "web_scraping",
    },
}

# Session 06 canary — the rung-1-vs-reference aggregate this script must
# reproduce exactly on the current taxonomy. A mismatch means the S06
# table is no longer reproducible and is a bigger finding than any rung 2
# number — report it, do not silently move on.
S06_CANARY = {
    "total_candidate": 61,
    "total_reference": 64,
    "total_agreed": 51,
    "micro_jaccard": 0.69,
}
CANARY_TOLERANCE = 0.01  # micro_jaccard only; counts must match exactly


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--own-resume",
        type=Path,
        required=True,
        help="Path to the own-resume file (mapped to the my_resume reference key).",
    )
    return parser.parse_args()


def build_resume_paths(own_resume: Path) -> dict[str, Path]:
    return {
        "prac_001": STRIPPED_DIR / "prac_001.pdf",
        "prac_006": STRIPPED_DIR / "prac_006.pdf",
        "prac_007": STRIPPED_DIR / "prac_007.docx",
        "my_resume": own_resume,
        "prac_014": STRIPPED_DIR / "prac_014.pdf",
        "prac_018": STRIPPED_DIR / "prac_018.pdf",
    }


def print_table(per_resume: list[PerResumeAgreement], aggregate: AggregateAgreement) -> None:
    print(f"  {'file':<12} {'candidate':>9} {'reference':>9} {'agreed':>6} {'jaccard':>7}")
    for row in per_resume:
        print(
            f"  {row.file:<12} {row.candidate_count:>9} {row.reference_count:>9} "
            f"{row.agreed_count:>6} {row.jaccard:>7.2f}"
        )
    print(
        f"  aggregate: total_candidate={aggregate.total_candidate} "
        f"total_reference={aggregate.total_reference} "
        f"total_agreed={aggregate.total_agreed} "
        f"precision_analogue={aggregate.precision_analogue:.2f} "
        f"recall_analogue={aggregate.recall_analogue:.2f} "
        f"micro_jaccard={aggregate.micro_jaccard:.2f}"
    )


def check_canary(aggregate: AggregateAgreement) -> bool:
    mismatches = []
    if aggregate.total_candidate != S06_CANARY["total_candidate"]:
        mismatches.append(
            f"total_candidate: expected {S06_CANARY['total_candidate']}, "
            f"got {aggregate.total_candidate}"
        )
    if aggregate.total_reference != S06_CANARY["total_reference"]:
        mismatches.append(
            f"total_reference: expected {S06_CANARY['total_reference']}, "
            f"got {aggregate.total_reference}"
        )
    if aggregate.total_agreed != S06_CANARY["total_agreed"]:
        mismatches.append(
            f"total_agreed: expected {S06_CANARY['total_agreed']}, got {aggregate.total_agreed}"
        )
    if abs(aggregate.micro_jaccard - S06_CANARY["micro_jaccard"]) > CANARY_TOLERANCE:
        mismatches.append(
            f"micro_jaccard: expected {S06_CANARY['micro_jaccard']} "
            f"(tolerance {CANARY_TOLERANCE}), got {aggregate.micro_jaccard:.4f}"
        )

    if mismatches:
        print("CANARY MISMATCH")
        for mismatch in mismatches:
            print(f"  {mismatch}")
        return False
    return True


def main() -> int:
    args = parse_args()
    taxonomy = load_taxonomy(TAXONOMY_DIR / "skills.yaml", TAXONOMY_DIR / "roles.yaml")
    resume_paths = build_resume_paths(args.own_resume)

    texts: dict[str, str] = {key: extract_resume_text(path) for key, path in resume_paths.items()}
    rung1_skills = {
        key: set(gazetteer.extract_skills(text, taxonomy)) for key, text in texts.items()
    }

    rung1_per_resume, rung1_aggregate = compute_agreement(rung1_skills, OPUS_REFERENCE)

    if not check_canary(rung1_aggregate):
        return 1

    print("rung 1 (gazetteer) vs reference:")
    print_table(rung1_per_resume, rung1_aggregate)

    rung2_skills = {
        key: set(embeddings.extract_skills(text, taxonomy)) for key, text in texts.items()
    }
    rung2_per_resume, rung2_aggregate = compute_agreement(rung2_skills, OPUS_REFERENCE)
    print()
    print("rung 2 (embeddings) vs reference:")
    print_table(rung2_per_resume, rung2_aggregate)

    return 0


if __name__ == "__main__":
    sys.exit(main())
